services:
  hounslow-bins:
    build: .
    # image: ghcr.io/ronschaeffer/hounslow_bin_collection:latest
    container_name: hounslow-bins
    restart: unless-stopped
    ports:
      - "${ICS_PORT:-8208}:8080"
    volumes:
      - ./config:/app/config
      - ./output:/app/output
    env_file:
      - .env
    environment:
      - CRON_SCHEDULE=${CRON_SCHEDULE:-50 2 * * *}
      - TZ=${TZ:-Europe/London}
